VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "cls_08aLoggedUserParams"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public lngUserID As Long
Public sUserLogin As String
Public sUserName As String
Public iUserSetor As Integer
Public sUserSetor As String

Public dictUserPermissions As Dictionary
    'UserLoginLevlsIDfk
    'UserLoginLevelDescriç





