VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "cls_03aCtrlsGrpsByForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Compare Database
Option Explicit

'Public cCtrL As Control     'Controle
Public sCtrlName As String  'Nome do [ TrggCtrl ] (apenas pra confirmação de acesso)
Public sFilGrp As String    'Grupo de filtragem a que pertence o controle
